OneBusAway/onebusaway-alexa

src/main/java/org/onebusaway/alexa/AnonSpeechlet.java
=> Speak stop code, not stop ID

pom.xml, src/test/java/config/UnitTests.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java, src/test/java/org/onebusaway/alexa/MainSpeechletEmptyTest.java
Addresses issue #18. I switched from Mockito to JMockit. This allows us to mock OBA libraries, so I wrote some new unit tests also.
=> Use JMockit; add unit tests

.travis.yml, pom.xml
=> Add support for Coveralls

src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/main/java/org/onebusaway/alexa/lib/ObaUserClient.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
=> Respond appropriately when there are no upcoming arrivals

interaction model/schema.json, interaction model/utterances.txt, src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java, src/test/java/org/onebusaway/alexa/MainSpeechletEmptyTest.java
=> Add skill help and more utterances

src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/main/java/org/onebusaway/alexa/lib/ObaClient.java, src/main/java/org/onebusaway/alexa/lib/ObaClientSharedCode.java, src/main/java/org/onebusaway/alexa/lib/ObaUserClient.java, src/test/java/org/onebusaway/alexa/MainSpeechletEmptyTest.java
As per discussion in issue #3.
Also, factor ObaClient and ObaUserClient into shared ObaClientSharedCode.
Lastly, remove a redundant unit test.
=> List regions when cannot find spoken city.

src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/main/java/org/onebusaway/alexa/lib/ObaClientSharedCode.java, src/main/java/org/onebusaway/alexa/lib/ObaUserClient.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java, src/test/java/org/onebusaway/alexa/MainSpeechletEmptyTest.java
And cleanup:
* Exception handling based on API call failures
* Use RegionUtils.isRegionUsable() instead of simple null check for ObaBaseUrl
* In getClosestRegion use List<> instead of ArrayList<> (library was updated)
@philipmw Please take a look.
=> Check API response code before returning result

src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/test/java/org/onebusaway/alexa/MainSpeechletEmptyTest.java
=> Handle missing slots (issues 28 and 29)

interaction model/utterances.txt
I tend to say "set my X to Y", and we didn't have utterances that map to that.
=> Add more utterances for setting city and stop

src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
=> Fix #39 - Use persisted info as session attributes for setting stop ID

src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
~~**Please don't merge yet**~~
~~* This successfully fixes the issue, but the tests still aren't passing.  Need to fix the tests and squash.~~
* Also update Tampa region name to "Tampa Bay"
=> Fix #42 - Only save persisted data to session if it doesn't exist

README.md
* http://onebusaway.org/privacy/
@philipmw Please take a look at the above link and see if I missed anything.
=> Add link to privacy policy at onebusaway.org

README.md, interaction model/customSlotTypes/TRANSIT_MODES, interaction model/schema.json, interaction model/utterances.txt
* Add "leave" and "departs" in addition to "arrives"
* Add most transit types that are listed in GTFS at https://developers.google.com/transit/gtfs/reference#routestxt.
* Add a few other phrases
=> Fix #48 - Add more utterances

src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
=> Reset unit-test session object between tests

pom.xml, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
For some MYSTERIOUS REASON, unit tests on master are failing on my workstation, but they pass in Travis CI. I fixed some mocking that I think make the tests more correct...
=> Fix unit tests

interaction model/schema.json, src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/main/java/org/onebusaway/alexa/ObaIntent.java, src/main/java/org/onebusaway/alexa/SessionAttribute.java, src/main/java/org/onebusaway/alexa/storage/ObaUserDataItem.java, src/test/java/config/UnitTests.java
=> Fix #49 - Implement AMAZON.RepeatIntent for arrivals, city, and stop

src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
Somehow PR #51 broke unit tests on master. This fixes them and adjusts repeat's implementation.
=> Mild refactor of repeat, fix unit tests

src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
Alright - here we are again :).
Last assert currently fails - I believe the issue is with the `obaDao` mocking.
=> Add test for repeat intent

src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java
* ...and calling methods.
* It's no longer needed after previous refactor in https://github.com/OneBusAway/onebusaway-alexa/pull/57.
=> Refactor session variable out of saving cached response method

src/main/java/org/onebusaway/alexa/LambdaFunctionHandler.java, src/main/java/org/onebusaway/alexa/config/AwsConfig.java, src/main/java/org/onebusaway/alexa/config/GoogleMapsConfig.java, src/main/java/org/onebusaway/alexa/config/ObaClientConfig.java, src/main/java/org/onebusaway/alexa/config/ObaProperty.java
* Also refactor property strings to constants
=> Fix #60 - Support multiple "skill-app-ids"

README.md, interaction model/customSlotTypes/AMAZON.US_CITY, interaction model/schema.json, interaction model/utterances.txt, src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/main/java/org/onebusaway/alexa/ObaIntent.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java, src/test/java/org/onebusaway/alexa/MainSpeechletEmptyTest.java, src/test/java/util/TestUtil.java
I'll keep pushing commits here to address various items in #63, and check them off the list there as they are completed.
=> Fix #63 - Address certification feedback

interaction model/utterances.txt
=> Add utterance 'stop {number}'

src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/main/java/org/onebusaway/alexa/lib/ObaUserClient.java, src/main/java/org/onebusaway/alexa/util/SpeechUtil.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
I'm going to push commits here as I work on this.
=> Fix #68 - Improve welcome onboard message

README.md
=> improve README order and formatting

interaction model/schema.json, src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/main/java/org/onebusaway/alexa/ObaIntent.java, src/main/java/org/onebusaway/alexa/SessionAttribute.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
=> Fix #53 - Disambiguate Stop Codes

src/main/java/org/onebusaway/alexa/AnonSpeechlet.java
=> Remove the word, Alexa for issue 88

src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/main/java/org/onebusaway/alexa/SessionAttribute.java, src/test/java/org/onebusaway/alexa/MainSpeechletEmptyTest.java
I've run this skill on my Echo to confirm the functionality works.
--These files already don't adhere to the OBA style template (e.g. 4 space tabs)
=> Fix #95 - Allow user to start bootstrap with stop id

interaction model/schema.json, interaction model/utterances.txt, src/main/java/org/onebusaway/alexa/AnonSpeechlet.java, src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/main/java/org/onebusaway/alexa/ObaIntent.java, src/main/java/org/onebusaway/alexa/SessionAttribute.java, src/main/java/org/onebusaway/alexa/lib/ObaUserClient.java, src/main/java/org/onebusaway/alexa/storage/ObaUserDataItem.java, src/main/java/org/onebusaway/alexa/util/SpeechUtil.java, src/test/java/config/UnitTests.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
* Apparently DynamoDB has problems persisting boolean and int values?  So we're using Long data types instead, with 0 being false and 1 being true.
* Add unit tests for clock time setting
=> Fix #97 - Add clock time configuration option

src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java
* I broke this intent in https://github.com/OneBusAway/onebusaway-alexa/pull/100, and the tests still passed, so we need better tests
=> Add more test cases for duplicate stop IDs

src/main/java/org/onebusaway/alexa/AuthedSpeechlet.java, src/main/java/org/onebusaway/alexa/SessionAttribute.java, src/main/java/org/onebusaway/alexa/storage/ObaUserDataItem.java, src/main/java/org/onebusaway/alexa/util/SessionUtil.java, src/main/java/org/onebusaway/alexa/util/SpeechUtil.java, src/main/java/org/onebusaway/alexa/util/StorageUtil.java, src/test/java/config/UnitTests.java, src/test/java/org/onebusaway/alexa/AuthedSpeechletTest.java, src/test/java/org/onebusaway/alexa/UtilTest.java
=> Fix #103 - Tell users about new features in a tutorial
